# Preload your wallpaper image into memory
#preload = /home/ping/Desktop/Wallpaper/a_bird_on_a_branch.png

# Set the wallpaper on monitor output (leave blank for all monitors)
#wallpaper = , /home/ping/Desktop/Wallpaper/a_bird_on_a_branch.png

# Disable splash text on start
#splash = false
