#!/usr/bin/env python3
"""Persist one Super+H setting and apply it to the live Hyprland session."""
import json
import os
import subprocess
import sys

JSON_PATH = os.path.expanduser("~/.config/hypr/user-settings.json")
LUA_PATH = os.path.expanduser("~/.config/hypr/user-settings.lua")
GET = os.path.expanduser("~/.config/eww/scripts/get-user-settings.py")

# Import defaults/view without running the reader as main.
sys.path.insert(0, os.path.dirname(GET))
import importlib.util

spec = importlib.util.spec_from_file_location("get_user_settings", GET)
getmod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(getmod)


def eval_lua(src):
    subprocess.run(
        ["hyprctl", "eval", src],
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def write_lua(data):
    def lit(v):
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, str):
            return json.dumps(v)
        if isinstance(v, float):
            return f"{v:.4f}".rstrip("0").rstrip(".")
        return str(int(v))

    keys = (
        "sensitivity",
        "scroll_factor",
        "gaps_in",
        "gaps_out",
        "rounding",
        "inactive_opacity",
        "animations",
        "accel_profile",
    )
    body = ",\n".join(f"  {k} = {lit(data[k])}" for k in keys)
    with open(LUA_PATH, "w", encoding="utf-8") as fh:
        fh.write("-- Generated by ~/.config/eww/scripts/set-user-setting.py\n")
        fh.write("return {\n" + body + ",\n}\n")


def apply(data):
    s = float(data["sensitivity"])
    scroll = float(data["scroll_factor"])
    gi = int(data["gaps_in"])
    go = int(data["gaps_out"])
    rnd = int(data["rounding"])
    op = float(data["inactive_opacity"])
    anim = "true" if data["animations"] else "false"
    accel = str(data["accel_profile"])
    eval_lua(f"hl.config({{ input = {{ sensitivity = {s} }} }})")
    eval_lua(f"hl.config({{ input = {{ accel_profile = {json.dumps(accel)} }} }})")
    eval_lua(f"hl.config({{ input = {{ touchpad = {{ scroll_factor = {scroll} }} }} }})")
    eval_lua(f"hl.config({{ general = {{ gaps_in = {gi}, gaps_out = {go} }} }})")
    eval_lua(f"hl.config({{ decoration = {{ rounding = {rnd}, inactive_opacity = {op} }} }})")
    eval_lua(f"hl.config({{ animations = {{ enabled = {anim} }} }})")


def clamp(n, lo, hi):
    return max(lo, min(hi, n))


def main():
    if len(sys.argv) < 3:
        sys.exit(1)
    key, raw = sys.argv[1], sys.argv[2]
    data = getmod.load()

    if key == "sensitivity_i":
        data["sensitivity"] = round(clamp(int(float(raw)), 0, 200) / 100.0 - 1.0, 2)
    elif key == "scroll_i":
        data["scroll_factor"] = round(clamp(int(float(raw)), 0, 100) / 100.0, 2)
    elif key == "gaps_in":
        data["gaps_in"] = clamp(int(float(raw)), 0, 40)
    elif key == "gaps_out":
        data["gaps_out"] = clamp(int(float(raw)), 0, 48)
    elif key == "rounding":
        data["rounding"] = clamp(int(float(raw)), 0, 28)
    elif key == "opacity_i":
        data["inactive_opacity"] = round(clamp(int(float(raw)), 40, 100) / 100.0, 2)
    elif key == "animations":
        if raw == "toggle":
            data["animations"] = not bool(data.get("animations", True))
        else:
            data["animations"] = raw.lower() in ("1", "true", "on")
    elif key == "accel_profile":
        if raw == "toggle":
            data["accel_profile"] = "adaptive" if data.get("accel_profile") == "flat" else "flat"
        else:
            data["accel_profile"] = "adaptive" if raw == "adaptive" else "flat"
    else:
        sys.exit(1)

    os.makedirs(os.path.dirname(JSON_PATH), exist_ok=True)
    with open(JSON_PATH, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")
    write_lua(data)
    apply(data)

    payload = json.dumps(getmod.view(data))
    env = os.environ.copy()
    env["PATH"] = os.path.expanduser("~/.local/bin") + ":" + env.get("PATH", "")
    subprocess.run(
        ["eww", "update", f"user-settings={payload}"],
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        env=env,
    )


if __name__ == "__main__":
    main()
